### ISSUE TITLE
Some of the new ASGS Features are missing hierarchical relationships

### ISSUE THREAD

**Issue by ashleysommer** [CSIRO-enviro-informatics/asgs-dataset#16]
These links _**are**_ present in the underlying ASGS WFS Data Tables

* SA1 to ILOC
  * `SA1.ILOC_CODE_2016 -> ILOC.ILOC_CODE_2016`
* SA4 to GCCSA
  * `SA4.CGGSA_CODE_2016 -> GCCSA.GCCSA_CODE_2016`

So we _do_ have links from existing main-line ASGS features to two of the new features...

And some relationships exist in the WFS properties table, but _**are always null**_:
* SA1 to RA is always null
  * `SA1.RA_CODE_2016 == NULL  -!-> RA.RA_CODE_2016`
* SA1 to UCL is always null
  * `SA1.UCL_CODE_2016 == NULL  -!-> UCL.UCL_CODE_2016`
* SA2 to SUA is always null
  * `SA2.SUA_CODE_2016 == NULL  -!-> SUA.SUA_CODE_2016`

And these hierarchical relationships _**are missing**_:
* ILOC to IARE doesn't exist
  * No way of knowing which IARE an ILOC is within
* IARE to IREG doesn't exist
  * No way of knowing which IREG an IARE is within
* UCL to SOSR doesn't exist
  * No way of knowing which SOSR an UCL is within
* SOSR to SOS doesn't exist
  * No way of knowing which SOS a SOSR is within

Theres a chance there are some kind of joining-tables or node-networks represented on an ABS WFS endpoint that I don't know about, but the main ASGS Feature WFS endpoints don't contain these relationships.

**Comment by ashleysommer** [comment]
We may have to compute these missing relationships geospatially using PostGIS and store them as an internal linkset, like we did with Geofabric's missing Catchment->DrainageDivision relationships.

**Comment by ashleysommer** [comment]
Ok, so I've worked out a (kinda hacky) way to infer the missing ILOC->IARE->IREG and UCL->SOSR->SOS hierarchy.
The relationships are encoded in the feature code.
Eg: ILOC id: 50800204 is 8 digits long.
It is within IARE: 508002 is 6 digits long,
it is within IREG: 508 is 3 digits long.
An ILOC can get its containing IARE by dropping off the last two digits.
An IARE can get its containing IREG by dropping off the last three digits.

Same deal with the UCL->SOSR->SOS hierarchy.

EDIT: also, you can get the State by taking just the first number (5). This gives ILOC->State, IARE->State, and IREG->State relationships.
relationship.

**Comment by jyucsiro** [comment]
@ashleysommer a little hacky, but it will work. 

some searching on the web yielded this from QLD Gov:
https://www.qgso.qld.gov.au/geographies-maps/geographic-hierarchy/meshblock-correspondence-file-asgs-2016
https://www.qgso.qld.gov.au/geographies-maps/geographic-hierarchy/sa1-correspondence-file-asgs-2016

looks like this group has calculated these for ASGS 2016. we might be able to use these?

**Comment by jyucsiro** [comment]
might want to validate if they are correct

**Comment by ashleysommer** [comment]
I've look at the QLD Gov correspondence tables, they are really handy, look accurate, and would suit our purpose. But are QLD only! I wonder how they calculated them.

So main issue now is the SA1->RA, SA1->UCL, and SA2->UAC connections. These are the ones where there is a linking column in the WFS properties, but the value of that column is always Null. I wonder if this is a bug in their WFS config, and perhaps need to be reported.

**Comment by jyucsiro** [comment]
Ah bummer. Yes, we should report an issue on this and have a fix in place in the meantime
