### ISSUE TITLE
Harvest updated asgsLd.net with new abs and non-abs structures and upload to s3 folder

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/asgs-dataset#22]

**Comment by ashleysommer** [comment]
Harvested and uploaded to S3 bucket called new-asgs

**Comment by jyucsiro** [comment]
thanks @ashleysommer. looks good and a lot more compact! 

we previously put all the harvested files in that s3 bucket but in a directory called `/auto-generated/datasets/` and as a one gzip. suggest we do the same with this one? perhaps add today's date in the filename also so we can point to it in our cache scripts.

**Comment by jyucsiro** [comment]
after discussion, decided we should rename `new-asgs` to something like `asgs2016_20200227` (with datestamp) and put it in `/auto-generated/datasets`

**Comment by benjaminleighton** [comment]
On further discussion the decision was to keep individual files separated and adjust the cache scripts to upload multiple component files of a dateset.
