### ISSUE TITLE
Use dataset IDs (code ID) for all ASGS 2016 URIs rather than names

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/asgs-dataset#7]
There were URIs created with names for states in ASGS 2016. The state URIs have duplicates with both names and codes. These were manually added for convenience to access ASGS STE URIs via label e.g. http://linked.data.gov.au/dataset/asgs2016/stateorterritory/ACT

It should be this instead:
http://linked.data.gov.au/dataset/asgs2016/stateorterritory/2

This issue implies we need to change the dataset and redeploy the asgsld.net pyldapi and cached dataset in s3.

**Comment by jyucsiro** [comment]
Relates to https://github.com/CSIRO-enviro-informatics/loci.cat/issues/11

**Comment by jyucsiro** [comment]
Will need this to be fixed before releasing IderDown v1 (see https://github.com/CSIRO-enviro-informatics/loci-excelerator)

**Comment by shaneseaton** [comment]
The code changes have been made, and the application redeployed. Its now ready for integration to the cache.
